name: Generate Daily Content
on:
  schedule:
    - cron: "10 5 * * *"
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python -m pip install --upgrade pip
      - run: python scripts/run_pipeline.py
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add frontend/pages/updates || true
          git commit -m "chore: daily generated updates" || echo "No changes"
      - run: git push
